name: ATCS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - pytorch=1.10.0
  - numpy=1.22.3
  - matplotlib=3.5.2
  - ipywidgets=7.7.0
  - jupyter=1.0.0
  - setuptools=59.5.0
  - pytorch-lightning=1.5.0
  - tabulate=0.8.9
  - tqdm=4.62.3
  - pillow=8.0.1
  - datasets=2.0.0
  - pip:
    - tensorboard==2.7.0
    - adapter-transformers==3.0.0
    - ray[tune]==1.12.1
