#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:2
#SBATCH --job-name=TrainSTAFusionJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=04:00:00
#SBATCH --mem=64000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Your job starts in the directory where you call sbatch
cd $HOME/project
# Activate your environment
source activate ATCS
# Run your code
srun python -u adapter_fusion.py
